Library/Areas/Admin/Models/Branches/BranchDetailModel.cs
using Library.Models.Catalog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Areas.Admin.Models.Branches
{
    public class BranchDetailModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Description { get; set; }
        public DateTime OpenDate { get; set; }
        public string ImageURL { get; set; }

        public string BranchOpenedDate { get; set; }
        public bool IsOpen { get; set; }

        public int NumberOfPatrons { get; set; }
        public int NumberOfAssets { get; set; }
        public decimal TotalAssetValue { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<string> HoursOpen { get; set; }
        public Dictionary<string, int> AssetsTitle { get; set; }

    }
}

Library/Areas/Admin/Models/Branches/BranchIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Areas.Admin.Models.Branches
{
    public class BranchIndexModel
    {
        public IEnumerable<BranchDetailModel> Branches { get; set; }
        public int TotalAssets { get; set; }
        public int TotalPatron { get; internal set; }
    }
}

Library/Models/Branch/BranchDetailModel.cs
using Library.Data.Models;
using Library.Models.Catalog;
using System.Collections.Generic;

namespace Library.Models.Branch
{
    public class BranchDetailModel
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string BranchName { get; set; }
        public string BranchOpenedDate { get; set; }
        public string Telephone { get; set; }
        public bool IsOpen { get; set; }
        public string Description { get; set; }
        public int NumberOfPatrons { get; set; }
        public int NumberOfAssets { get; set; }
        public decimal TotalAssetValue { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<string> HoursOpen { get; set; }
        public string AssetsTitle { get; set; }
        public int TotalAssets { get; set; }
    }
}

Library/Models/Branch/BranchIndexModel.cs
using System.Collections.Generic;

namespace Library.Models.Branch
{
    public class BranchIndexModel
    {
        public IEnumerable<BranchDetailModel> Branches { get; set; }
        public int TotalAssets { get; set; }
    }
}

Library/Areas/Admin/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Areas.Admin.Models.Branches;
using Library.Data.Models;
using LibraryData;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Library.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class BranchesController : Controller
    {
        private ILibraryBranchService _branch;
        private readonly IWebHostEnvironment he;
        public BranchesController(ILibraryBranchService branch, IWebHostEnvironment e)
        {
            _branch = branch;
            he = e;
        }
        public IActionResult CreateBranch(LibraryBranch newBranch, IFormFile ImageUrl)
        {
            newBranch.ImageUrl = "/images/branch/" + ImageUrl.FileName;
            _branch.Add(newBranch);
            if (ImageUrl != null)
            {
                var fileName = Path.Combine(he.WebRootPath + "/images/branch", Path.GetFileName(ImageUrl.FileName));
                ImageUrl.CopyTo(new FileStream(fileName, FileMode.Create));
            }
            return RedirectToAction("ListBranch");
        }
        public IActionResult AddBranch(LibraryBranch newBranch, IFormFile ImageUrl)
        {
            return View();
        }
            public IActionResult ListBranch()
        {
            var branch = _branch.GetAll();
            var List = branch
                       .Select(result => new BranchDetailModel
                       {
                           Id = result.Id,
                           ImageURL = result.ImageUrl,
                           Name = result.Name,
                           Address = result.Address,
                           Telephone = result.Telephone,
                           Description = result.Description,
                           OpenDate = result.OpenDate,           
                           NumberOfAssets = _branch.GetAssetCount(result.Id),
                           NumberOfPatrons = _branch.GetPatronCount(result.Id),
                           IsOpen = _branch.IsBranchOpen(result.Id)
                           
                       });
            var model_branch = new BranchIndexModel()
            {
                Branches = List
            };
            return View(model_branch);
        }
        public IActionResult Delete(int id)
        {
            _branch.Remove(id);
            return RedirectToAction("ListBranch");
        }

        public IActionResult EditBranch(int id)
        {
            var branch = _branch.GetById(id);
            var model = new BranchDetailModel
            {
                Id = branch.Id,
                ImageURL = branch.ImageUrl,
                Name = branch.Name,
                Address = branch.Address,
                Telephone = branch.Telephone,
                Description = branch.Description,
                OpenDate = branch.OpenDate
            };
            return View(model);
        }


        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(BranchDetailModel branch, IFormFile ImageUrl)
        {
            string message = "";
            var data = _branch.GetById(branch.Id);
                data.Id = branch.Id;
                data.Name = branch.Name;
                data.Address = branch.Address;
                data.Telephone = branch.Telephone;
                data.Description = branch.Description;
                data.OpenDate = branch.OpenDate;

            if (ImageUrl != null)
            {
                branch.ImageURL = "/images/branch/" + ImageUrl.FileName;
                data.ImageUrl = branch.ImageURL;
                var fileName = Path.Combine(he.WebRootPath + "/images/branch", Path.GetFileName(ImageUrl.FileName));
                ImageUrl.CopyTo(new FileStream(fileName, FileMode.Create));
            }
            bool result = _branch.Update(data);
            if (result)
            {
                message += "Update succesfully!";
            }    
            else
            {
                message += "Fail to update";
            }    
             //return Content(message);
            return RedirectToAction("ListBranch");
        }
    }
}

Library/Areas/Employee/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Branch;
using LibraryData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Library.Areas.Employee.Controllers
{
    [Area("Employee")]
   
    public class BranchController : Controller
    {
        private readonly ILibraryBranchService _branchService;

        public BranchController(ILibraryBranchService branchService)
        {
            _branchService = branchService;
        }
       
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else if (HttpContext.Session.GetInt32("role_id") == 3)
                return RedirectToAction("Login", "Home");
            else
            {
                 var branchModels = _branchService.GetAll()
                .Select(br => new BranchDetailModel
                {
                    Id = br.Id,
                    BranchName = br.Name,
                    NumberOfAssets = _branchService.GetAssetCount(br.Id),
                    NumberOfPatrons = _branchService.GetPatronCount(br.Id),
                    IsOpen = _branchService.IsBranchOpen(br.Id)
                }).ToList();

            var model = new BranchIndexModel
            {
                Branches = branchModels
            };

            return View(model);
            }

        }
        public IActionResult Detail(int id)
        {
            var branch = _branchService.Get(id);
            var model = new BranchDetailModel
            {
                BranchName = branch.Name,
                Description = branch.Description,
                Address = branch.Address,
                Telephone = branch.Telephone,
                BranchOpenedDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = _branchService.GetPatronCount(id),
                NumberOfAssets = _branchService.GetAssetCount(id),
                TotalAssetValue = _branchService.GetAssetsValue(id),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branchService.GetBranchHours(id)
            };

            return View(model);
        }
    }
}

Library/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Areas.Admin.Models.Branches;
using LibraryData;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
  
   
    public class BranchController : Controller
    {
        private readonly ILibraryBranchService _branchService;

        public BranchController(ILibraryBranchService branchService)
        {
            _branchService = branchService;
        }
       
        public IActionResult Index()
        {
            var branchModels = _branchService.GetAll()
                .Select(br => new BranchDetailModel
                {
                    Id = br.Id,
                    Name = br.Name,
                    NumberOfAssets = _branchService.GetAssetCount(br.Id),
                    NumberOfPatrons = _branchService.GetPatronCount(br.Id),
                    IsOpen = _branchService.IsBranchOpen(br.Id)
                }).ToList();

            var model = new BranchIndexModel
            {
                Branches = branchModels
            };

            return View(model);
        }
        public IActionResult Detail(int id)
        {
            var branch = _branchService.Get(id);
            var model = new BranchDetailModel
            {
                Name = branch.Name,
                Description = branch.Description,
                Address = branch.Address,
                Telephone = branch.Telephone,
                ImageURL = branch.ImageUrl,
                BranchOpenedDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = _branchService.GetPatronCount(id),
                NumberOfAssets = _branchService.GetAssetCount(id),
                TotalAssetValue = _branchService.GetAssetsValue(id),
          
                HoursOpen = _branchService.GetBranchHours(id),
                AssetsTitle = _branchService.GetAssetsTitle(id)

            };

            return View(model);
        }
    }
}

Library/Areas/Employee/Views/Branch/Detail.cshtml
@using Library.Models.Branch
@model Library.Models.Branch.BranchDetailModel
@{
    ViewBag.Title = @Model.BranchName + " Branch";
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
}


<div class="container">
    
    <div class="jumbotron">
        <div class="row">
            <img src="@Model.ImageUrl" style="max-width:300px; max-height: 450px" />
        </div>
        <div class="row">
            <h2>@Model.BranchName</h2>
        </div>
        <div class="row branchInfo">
            <div class="col-md-8">
                <div>

                    <div class="branchContact">
                        <div id="branchAddress">Address: @Model.Address</div>
                        <div id="branchTel">Telephone: @Model.Telephone</div>
                    </div>
                    <div id="branchDescription">
                        <p class="caption">@Model.Description</p>
                    </div>

                    <div id="branchHours">
                        <ul>
                            @foreach (var day in @Model.HoursOpen)
                            {
                                <li>@day</li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 detailInfo">
                <table>
                    <tr>
                        <td class="itemLabel">Date Opened: </td>
                        <td class="itemValue">@Model.BranchOpenedDate</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Number Of Patrons: </td>
                        <td class="itemValue">@Model.NumberOfPatrons</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Number of Assets: </td>
                        <td class="itemValue">@Model.NumberOfAssets</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Value of Assets: </td>
                        <td class="itemValue">$@Model.TotalAssetValue</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

Library/Areas/Employee/Views/Branch/Index.cshtml
@using Library.Models.Branch
@model Library.Models.Branch.BranchIndexModel
@{
    ViewBag.Title = "Branch Index";
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
}
<h3>Branches</h3>
<div id="branchIndex">
    <table class="table table-condensed" id=" catalogIndexTable">
        <thead>
            <tr>
                <th>Branch Name</th>
                <th>Open Now</th>
                <th>Number Of Assets</th>
                <th>Number of Patrons</th>          
            </tr>
        </thead>
        <tbody>
            @foreach (var branch in Model.Branches)
            {
            <tr>
                <td class="strongTd"><a asp-controller="Branch" asp-action="Detail" asp-route-id="@branch.Id">@branch.BranchName</a></td>
                <td>@branch.IsOpen</td>
                <td>@branch.NumberOfAssets</td>
                <td>@branch.NumberOfPatrons</td>
            
            </tr>
            }
        </tbody>
    </table>
</div>