Library/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Catalog;
using Library.Models.CheckoutModels;
using LibraryData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;
        private ICheckout _checkouts;

        public CatalogController(ILibraryAsset assets, ICheckout checkouts)
        {
            _assets = assets;
            _checkouts = checkouts;
        }
        public IActionResult Index()
        {
            var assetModels = _assets.GetAll();
            var ListingResult = assetModels
                        .Select(result => new AssetIndexListingModel
                        {
                            Id = result.Id,
                            ImageURL = result.ImageUrl,
                            AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                            DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                            Title = result.Title,
                            Type = _assets.GetType(result.Id),
                            CurrentLocation = _assets.GetCurrentLocation(result.Id)?.Name

                        });
            var model = new AssetIndexModel()
            {
                Assets = ListingResult
            };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            int libCard = 0;
            bool isLogin = false;
            if (HttpContext.Session.GetString("username") != null)
            {
                 libCard = (int)HttpContext.Session.GetInt32("LibraryCard");
                isLogin = true;
            }

            var asset = _assets.GetById(id);
            var currentHolds = _checkouts.GetCurrentHold(id)
                .Select(a => new AssetHoldModel
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id).ToString(),
                    PatronName = _checkouts.GetCurrentHoldPatron(a.Id)
                });
            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Type = _assets.GetType(id),
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector(id), //Ham duoc viet cho lop Interface -  Services
                CurrentLocation = _assets.GetCurrentLocation(id)?.Name,
                Dewey = _assets.GetDeweyIndex(id),
                Isbn = _assets.GetIsbn(id),
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                CurrentAssociatedLibraryCard = _assets.GetLibraryCardByAssetId(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentPatron(id),
                CheckHoldExist = _checkouts.CheckHoldExist(id, libCard),
                CurrentHolds = currentHolds,
                IsLogin = isLogin
            };
            string msg = "";
            msg += _checkouts.CheckHoldExist(id,libCard);
            return View(model);
            //msg += libCard;
            //return Content(msg);
        }

        public IActionResult Hold(int id) //Giu sach
        {
            var asset = _assets.Get(id);
            //HttpContext.Session.SetInt32("LibraryCard", patron_id.LibraryCard.Id);
           // msg += HttpContext.Session.GetInt32("LibraryCard");
            //msg += HttpContext.Session.GetString("username");
            var libCard = HttpContext.Session.GetInt32("LibraryCard");
            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = libCard.ToString(),
                HoldCount = _checkouts.GetCurrentHold(id).Count()
            };

            return View(model);
            //return Content(msg);

        }

        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult Search(string searchString)
        {
            var assetModels = _assets.GetAllWith(searchString);
            var ListingResult = assetModels
                        .Select(result => new AssetIndexListingModel
                        {
                            Id = result.Id,
                            ImageURL = result.ImageUrl,
                            AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                            DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                            Title = result.Title,
                            Type = _assets.GetType(result.Id),
                            CurrentLocation = _assets.GetCurrentLocation(result.Id)?.Name

                        });
            var model = new AssetIndexModel()
            {
                Assets = ListingResult
            };
            return View("Index", model);
        }
    }
}   

Library/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Areas.Admin.Models.Branches;
using Library.Data.Models;
using Library.Models.CheckoutModels;
using Library.Models.Patron;
using LibraryData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;

namespace Library.Controllers
{
    public class PatronController : Controller
    {
        private readonly IPatron _patronService;
        private readonly ILibraryBranchService _branch;

        public PatronController(IPatron patronService, ILibraryBranchService branch)
        {
            _patronService = patronService;
            _branch = branch;
          
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public IActionResult SubmitLogin(Patron patron)
        {         
            bool result = _patronService.Authorize(patron.Username, patron.Password);
            var patron_id = _patronService.GetByUsername(patron.Username);
          
            if (result)
            {
                HttpContext.Session.SetString("username", patron.Username);
                HttpContext.Session.SetInt32("id", patron_id.Id);
                HttpContext.Session.SetInt32("LibraryCard", patron_id.LibraryCard.Id);
                HttpContext.Session.SetInt32("role_id", patron_id.RoleID);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.error = "Invalid Account";
                return View("Login");
            }                
            
        }
       
        public IActionResult Profile(int id)
        {
            string msg = "";
            var patron = _patronService.Get(id);
           
            msg += HttpContext.Session.GetString("username");
            var model = new PatronDetailModel
            {
                Username = patron.Username,
                Id = patron.Id,
                LastName = patron.LastName ?? "No Last Name Provided",
                FirstName = patron.FirstName ?? "No First Name Provided",
                Address = patron.Address ?? "No Address Provided",
                HomeLibrary = patron.HomeLibraryBranch?.Name ?? "No Home Library",
                MemberSince = patron.LibraryCard?.Created,
                OverdueFees = patron.LibraryCard?.Fees,
                LibraryCardId = patron.LibraryCard?.Id,
                Telephone = string.IsNullOrEmpty(patron.TelephoneNumber) ? "No Telephone Number Provided" : patron.TelephoneNumber,
                AssetsCheckedOut = _patronService.GetCheckouts(id).ToList(),
                CheckoutHistory = _patronService.GetCheckoutHistory(id),
                Holds = _patronService.GetHolds(id)

            };
           // return Content(msg);
            return View(model);
        }
        public IActionResult EditInfo(int id)
        {
            var list = _branch.GetAll();
            IEnumerable<BranchDetailModel> ResultBranch = list.
                            Select(result => new BranchDetailModel
                            {
                                Id = result.Id,
                                Name = result.Name,
                            });
            List<BranchDetailModel> listBranch = ResultBranch.ToList();
            SelectList branchList = new SelectList(listBranch, "Id", "Name");
            ViewBag.branchList = branchList;         

            var patron = _patronService.Get(id);
            var model = new PatronDetailModel
            {
                Id = id,
                FirstName = patron.FirstName,
                LastName = patron.LastName,
                Address = patron.Address,
                Telephone = patron.TelephoneNumber,
                LibraryCardId = patron.LibraryCardId,
                Email = patron.Email,
                DateOfBirth = patron.DateOfBirth
            };
            return View(model);

        }
        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(PatronDetailModel patron)
        {
            var data = _patronService.Get(patron.Id);
            if (ModelState.IsValid)
            {
                data.Id = patron.Id;
                data.FirstName = patron.FirstName;
                data.LastName = patron.LastName;
                data.TelephoneNumber = patron.Telephone;
                data.Email = patron.Email;
                data.Address = patron.Address;
                data.DateOfBirth = patron.DateOfBirth;
                data.HomeLibraryBranchId = patron.HomeLibraryBranchId;
                if (patron.Password != null)
                {
                    data.Password = patron.Password;
                }    
                bool result = _patronService.Update(data);
            }
            else
            {
                ViewBag.Error = "Missing value";
            }

            var patrondetail = _patronService.Get(patron.Id);
            var model = new PatronDetailModel
            {
                Id = patrondetail.Id,
                LastName = patrondetail.LastName ?? "No Last Name Provided",
                FirstName = patrondetail.FirstName ?? "No First Name Provided",
                Address = patrondetail.Address ?? "No Address Provided",
                HomeLibrary = patrondetail.HomeLibraryBranch?.Name ?? "No Home Library",
                MemberSince = patrondetail.LibraryCard?.Created,
                OverdueFees = patrondetail.LibraryCard?.Fees,
                LibraryCardId = patrondetail.LibraryCard?.Id,
                Telephone = string.IsNullOrEmpty(patrondetail.TelephoneNumber) ? "No Telephone Number Provided" : patrondetail.TelephoneNumber,
                AssetsCheckedOut = _patronService.GetCheckouts(patron.Id).ToList(),
                CheckoutHistory = _patronService.GetCheckoutHistory(patron.Id),
                Holds = _patronService.GetHolds(patron.Id)
            };
            return View("Profile", model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]

        public JsonResult CheckUsername(string username, string email )
        {           
            var result = _patronService.CheckUserExist(username, email);
            if (result) return Json("1");
            
            return Json("0");
        }

        public JsonResult CheckCurrentPass(int id,string current)
        {
            var result = _patronService.CheckCurrentPass(id,current);
            if (result) return Json("0");

            return Json("1");
        }
        public IActionResult RegisterForm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SubmitRegister(Patron patron)
        {
            LibraryCard libCard = new LibraryCard();
            var now = DateTime.Now;
            libCard.Fees = 0;
            libCard.Created = now;
            var idCard = _patronService.AddNewLibraryCard(libCard);
            patron.LibraryCardId = idCard;
            patron.HomeLibraryBranchId = 1;
            patron.RoleID = 3;
            _patronService.AddNewPatron(patron);
            return View("Login");
        }

       
    }
}

Library/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <title>LIBRARY</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Oxygen:400,700" rel="stylesheet">

    <link rel="stylesheet" href="~/Assets/general/css/animate.css">
    <link rel="stylesheet" href="~/Assets/general/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/general/css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="~/Assets/general/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/general/fonts/fontawesome/css/font-awesome.min.css">

    <!-- Theme Style -->
    <link rel="stylesheet" href="~/Assets/general/css/style.css">


</head>

<body>
    <header role="banner" style="background-color: black;">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand " asp-controller="Home" asp-action="Index">OUR LIBRARY</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample05">
                    <ul class="navbar-nav pl-md-5 ml-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " href="#about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#contact">Contact</a>
                        </li>
                        <li class="nav-item dropdown">
                            @if (@Context.Session.GetString("username") == null)
                            {<a class="nav-link" id="dropdown04" asp-controller="Patron" asp-action="Login" >LOGIN</a>
                            }
                            else
                            {
                                <a class="nav-link dropdown-toggle" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Context.Session.GetString("username")</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown04">

                                    <a class="dropdown-item" asp-controller="Patron" asp-action="Profile" asp-route-id='@Context.Session.GetInt32("id")'>Profile</a>
                                    <a class="dropdown-item" asp-controller="Patron" asp-action="EditInfo" asp-route-id='@Context.Session.GetInt32("id")'>Account setting</a>
                                    <a class="dropdown-item" asp-controller="Patron" asp-action="Logout">Log out</a>
                                    
                                </div>
                            }


                        </li>
                    </ul>


                </div>
            </div>
        </nav>
    </header>


    <div class="top-shadow"></div>

    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">


        <div class="page-content">
            @RenderBody()

            <footer class="site-footer" role="contentinfo">
                <div class="container">
                    <div class="row mb-5" id="about">
                        <div class="col-md-4 mb-5">
                            <h3>About Us</h3>
                            <p class="mb-2">Infomation System</p>
                            <p class="mb-2">Project name: A Library management system</p>
                            <p class="mb-2">Instructor: Mai Xuan Hung</p>
                            <ul class="list-unstyled footer-link d-flex footer-social">
                                <li><a href="#" class="p-2"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#" class="p-2"><span class="fa fa-facebook"></span></a></li>
                                <li><a href="#" class="p-2"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#" class="p-2"><span class="fa fa-instagram"></span></a></li>
                            </ul>

                        </div>
                        <div class="col-md-5 mb-5 pl-md-5" id="contact">
                            <h3>Contact Info</h3>
                            <ul class="list-unstyled footer-link">
                                <li class="d-block">
                                    <span class="d-block">Address:</span>
                                    <span>University of Infomation Technology, HCM National University, HCM City</span>
                                </li>
                                <li class="d-block"><span class="d-block">Telephone:</span><span>+84 388 197 156</span></li>
                                <li class="d-block"><span class="d-block">Email:</span><span>mnngoc105@gmail.com</span></li>
                            </ul>
                        </div>

                        <div class="col-md-3">
                            <h3>Member</h3>
                            <ul class="list-unstyled footer-link">
                                <li class="d-block">Mai Nhu Ngoc</li>
                                <li class="d-block">Nguyen Phi Yen</li>
                                <li class="d-block">Tran Huu Phat</li>
                                <li class="d-block">Nguyen Huu Phuoc</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-md-center text-left">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>

    <script src="~/Assets/general/js/jquery-3.2.1.min.js"></script>
    <script src="~/Assets/general/js/popper.min.js"></script>
    <script src="~/Assets/general/js/bootstrap.min.js"></script>
    <script src="~/Assets/general/js/owl.carousel.min.js"></script>
    <script src="~/Assets/general/js/jquery.waypoints.min.js"></script>
    <script src="~/Assets/general/js/jquery.fancybox.min.js"></script>
    <script src="~/Assets/general/js/main.js"></script>

    <script src="~/Assets/general/js/main.js"></script>
</body>
</html>